server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://stats-db:5432/statsdb
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
  sql:
    init:
      mode: always
  hibernate:
    jdbc:
      time_zone: UTC

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.springframework.web.client: DEBUG
    feign: DEBUG