collector:
  kafka:
    bootstrapServers: "localhost:9092"
    clientIdConfig: "collector-client"
    producerKeySerializer: org.apache.kafka.common.serialization.LongSerializer
    producerValueSerializer: ru.yandex.practicum.serializer.GeneralAvroSerializer
    userActionTopic: "stats.user-actions.v1"
