server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # 1. CATEGORY-SERVICE
        - id: public_categories_route
          uri: lb://category-service
          predicates:
            - Path=/categories/**
        - id: admin_categories_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**

        # 2. EVENT-SERVICE (События и Подборки)
        - id: public_compilations_route
          uri: lb://event-service
          predicates:
            - Path=/compilations/**
        - id: admin_compilations_route
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**
        - id: public_events_route
          uri: lb://event-service
          predicates:
            - Path=/events/**
        - id: admin_events_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**
        - id: private_user_events_route
          uri: lb://event-service
          predicates:
            - Path=/users/*/events/**

        # 3. REQUEST-SERVICE (Запросы на участие)
        - id: private_user_requests_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**
            - Path=/users/*/events/*/requests/**

        # 4. USER-SERVICE
        - id: admin_users_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        # 5. STATS-SERVICE
        - id: internal_stats_route
          uri: lb://stats-server # ВНИМАНИЕ: В Eureka он зарегистрирован как STATS-SERVER (с буквой S), а не stats-service
          predicates:
            - Path=/stats/**, /hit/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty: DEBUG